### ISSUE TITLE
All Colonists Died No Food In Stockpile So Cant Spawn New Colonists 

### ISSUE THREAD

**Issue by Swifty1323** [pipliz/ColonySurvival#106]
my friend and I were playing and all of his colonists died. He has no food in his stockpile so he cant spawn in new colonists. Do we just have to restart?

**Comment by Swifty1323** [comment]
Oh also, it won't let us use the /loot command

**Comment by pipliz** [comment]
Assuming it's http://steamcommunity.com/app/366090/discussions/4/2765630416819973399/?tscn=1505677116 , seems 'solved'.
