### ISSUE TITLE
Science issues

### ISSUE THREAD

**Issue by JBurlison** [pipliz/ColonySurvival#113]
My colonist is getting all the mats from the stockpile, going to the crafting table then going back to the crate to put the mats back. and repeating. This is only with custom research added with my [Mod](https://github.com/JBurlison/Pandaros.Settlers)

So there's that and the 6-wide half hidden research icons. You can see a sliver of the hidden ones to the left of the scroll bar.
![6 columns](https://cdn.discordapp.com/attachments/345198149343772672/361631480801394708/unknown.png)

![ENHANCE!](https://cdn.discordapp.com/attachments/345198149343772672/361632347231223811/unknown.png)

**Comment by pipliz** [comment]
Fixed missing researches.

I replicated the walking back and forth colonists in 0.3.0, but seems to be already fixed in 0.4.0 (when I change an existing research to have the same requirements, since the mod won't work).

**Comment by JBurlison** [comment]
I could build a version compatible with the next release if you would like?
