### ISSUE TITLE
Additional Monster/NPC properties and callbacks

### ISSUE THREAD

**Issue by JBurlison** [pipliz/ColonySurvival#115]
It would be super useful if NPCs and zombies had a dictionary similar to player GetTemporaryValue / SetTemporaryValue.

Also a call back for when a NPC/Monster is created or destroyed. Make on the constructors and the onragdoll/ondeath?

**Comment by JBurlison** [comment]
Is it possible to get a callback when a monster is hit also?

**Comment by pipliz** [comment]
Fully implemented
