### ISSUE TITLE
Science categories 

### ISSUE THREAD

**Issue by JBurlison** [pipliz/ColonySurvival#116]
![science](https://media.discordapp.net/attachments/345198149343772672/361631480801394708/unknown.png)

I think A lot of mods are going to be adding science, so as they do it would be nice to add tabs on this either vertical along the side or along top with all the categories so mods can categorize their research.

![image](https://user-images.githubusercontent.com/1290966/30925525-267f2f00-a380-11e7-9a4c-55c600bde4f0.png)

maybe they are just filters? Also maybe add something to the icons like add a gray overlay when they do not have the materials.

maybe the tech has a horizontal scroll similar to CIV and you can lay them out according to requirements. Like:
![image](http://well-of-souls.com/civ/images/vexing_332techs_original.jpg)

**Comment by pipliz** [comment]
We'll see if we need something after implementing all the researches coming in 0.4.0

**Comment by pipliz** [comment]
Clarity for vanilla science seems to be mostly resolved with some minor tweaks that happened, like having division bars and using grayed out icons instead of color outlines. Categories would be overkill for vanilla yet would still be there
