### ISSUE TITLE
HandleD3DDeviceLost errors leading to crash

### ISSUE THREAD

**Issue by 82280zx** [pipliz/ColonySurvival#130]
Everyone's colony's disappeared, our buildings was still there but Beds, Colonists and Jobs was all gone, we had to pick up everything and put them back down to restart everything. Possible flag bug? We also had to pick up our flag and put it back down before we could recruit colonists. 

[2017-10-31_200258.zip](https://github.com/pipliz/ColonySurvival/files/1435287/2017-10-31_200258.zip)

**Comment by pipliz** [comment]
Searching around for the spammed errors in the log file "D3Dwindow device not lost anymore" leads me to suspect this is an issue with unity related to locking the screen or entering the screensaver. There's not a lot I can do at the moment, but I do plan a way to launch the server through a commandline window which would mean unity does not need to render anything and thus preventing this bug.
