### ISSUE TITLE
Colonist staying in wheatfield? cannot find its bed?

### ISSUE THREAD

**Issue by acidballoons** [pipliz/ColonySurvival#132]

**Comment by pipliz** [comment]
Can you give a bit more details? Does the npc get an indicator above its head?

**Comment by acidballoons** [comment]
Yeah, everynight some of them just stay in their fields and resume work in the morning, that's if the zombies don't get them first. they get the indicator and everytime it resets they just don't move, i've restarted the game since though so it might just be a 1 time thing
