### ISSUE TITLE
Can I run it using openGl?

### ISSUE THREAD

**Issue by ghost** [pipliz/ColonySurvival#133]
My computer don't have directX 11 support, have some method to run that with directX 10 or 9, or run with opengl?

**Comment by pipliz** [comment]
It can run on directx 11, 12 and openGL, but it requires some hardware functions that came with directX 11 to function properly.

If you have a copy of the game, you can try by launching it with the command line argument:
> -force-glcore

**Comment by ghost** [comment]
With this parameter the game crashs instantly, you need the dump files?

**Comment by ghost** [comment]
[error.log](https://github.com/pipliz/ColonySurvival/files/1443152/error.log)
[output_log.txt](https://github.com/pipliz/ColonySurvival/files/1443153/output_log.txt)

my system specs: 

Pentium(R) Dual-Core CPU T4300 @ 2.10GHz 2.10 GHz
3.00Gb RAM
Windows 7 Ultimate SP1 x64
Mobile Intel(R) 4 Series Express Chipset Family(1293Mb ramv)

DirectX version: 11
OpenGL version: 2.1
![image](https://user-images.githubusercontent.com/17722403/32404815-70f9caf4-c13f-11e7-8c87-67a12ea9e615.png)
"Versão do DirectX" = Version Of DirectX
![image](https://user-images.githubusercontent.com/17722403/32404826-bbc485ce-c13f-11e7-8a49-6590efd2d2b4.png)
The dxdiag shows me I have the directX 11 but my opengl version checker says I have the 9, 10.

**Comment by ghost** [comment]
Is just a black scream, and no, I'll not need the refund, thanks for the help :D

**Comment by pipliz** [comment]
The version number needed is the lower one: "DirectX 9, 10.0" & "shader models 4". These are the hardware support versions. Currently it requires hardware support for DirectX 11 & shader model 5.

If you want a refund and need help getting one, please mail us at pipliznl @ gmail.com.

Just to be curious, what does the game do when playing under directX 11? Does it render black/pink?
