### ISSUE TITLE
Foreground Is Always Black

### ISSUE THREAD

**Issue by HarvDad** [pipliz/ColonySurvival#14]
SETUP
    ASUS X501A (Laptop)
    OS:   SteamOS GNU/Linux 2.0 (brewmaster) 64 bit

    CPU:  Intel Core i3-2350M @ 2.30GHz x 4
    GPU:  Intel Sandybridge Mobile
    RAM:  8 GB
    Disk: 300 GB

    Resolution: 1366x768  (No obvious way to change this)

PROBLEM
No matter which way I face, no matter what time of day, the foreground is virtually blacked out, while the sky and clouds look fine.  None of the video settings seem to affect the foreground.
![screen_2017-07-01_15-20-29](https://user-images.githubusercontent.com/1504774/27809522-3c253aca-6005-11e7-9c91-08130e3609fc.png)

For reference, here are other games on the same system:

Minecraft
![minecraft](https://user-images.githubusercontent.com/1504774/27809625-3869f5aa-6006-11e7-9b85-335988375848.png)

Rising World
![risingworld](https://user-images.githubusercontent.com/1504774/27809582-c9c5ec80-6005-11e7-80c4-0d47f9399ab5.jpg)

If this is not a proper way to report such things, just let me know.
- Harv

**Comment by HarvDad** [comment]
I've seen the suggestion that if all textures are black it's most likely an openGL problem.  Namely, it's out of date.  I'm trying now to figure out how to update that on this computer, or at least find out if it's possible.

**Comment by pipliz** [comment]
Hey there. Sorry to say so but the Intel Core i3-2350M seems to only support up to directx 10.1 & openGL 3.3. The game requires directX 11 and/or openGL 4 (.2 or .3, not exactly sure without looking it up).
