### ISSUE TITLE
Chat window enhancements

### ISSUE THREAD

**Issue by JBurlison** [pipliz/ColonySurvival#150]
Some enhancements:

- Scroll-able (with a scrollbar or up/down arrows)
- Pressing the up/down arrows allows you to re-send messages similar to command prompt
- Help command that shows all available commands. This means adding a call to the chat command interface for available commands.

**Comment by JBurlison** [comment]
* Chat Tabs!

Make the tabs moddable. Mods should be able to write to a specific chat tab. Also, a callback for when text is sent to a chat tab.

**Comment by pipliz** [comment]
Merged into #322
