### ISSUE TITLE
Dedicated Server - NetworkType SteamLAN is still publicly listed

### ISSUE THREAD

**Issue by sordidfellow** [pipliz/ColonySurvival#151]
Of the available network types:
` +server.networktype     - Network type to host as, options are Singleplayer (connects to client), LAN (localhost client connects), SteamLAN, SteamOnline`

SteamLAN appears to be the one for Unlisted servers.
However, using the option still results in the server being publicly listed (and randoms joining).  Here is the command I used inside of colonyserverdedicated.exe:
`start_server +server.world FirstWorld +server.name "A Private Server" +server.networktype "SteamLAN" +server.maxplayers 4`

**Comment by pipliz** [comment]
Yes, I'm sorry for this. Currently there is no proper LAN mode. SteamLAN disables some authentication and does not automatically port forward. To prevent it from being listed, I'd recommend to try and block the query/game port used (default 27016) in a firewall or NAT or somewhere like that. I'd give that a 90% chance of working.

The other option is to try and use the whitelist file (gamedata/savegames/whitelist.txt).

We do of course have plans to fix this, but I am not sure when this will be enough of a priority to be implemented.

**Comment by pipliz** [comment]
Solved for next update
