### ISSUE TITLE
atidxx64.dll caused an Access Violation (0xc0000005)   in module atidxx64.dll at 0033:3bb840a4.

### ISSUE THREAD

**Issue by RedTailedMink** [pipliz/ColonySurvival#157]
crash dump is attached
[2017-11-22_224802.zip](https://github.com/pipliz/ColonySurvival/files/1498078/2017-11-22_224802.zip)

**Comment by pipliz** [comment]
Hi there. As the dll name sort of suggests, it looks like the AMD graphics driver crashed.

For previous crash reports it helped to set the game as an exception in their antivirus, that may be a thing you can try.

I'd normally also recommend updating the graphics drivers, but it seems you're already running the newest.

Sorry that I can't be of more help
