### ISSUE TITLE
 GetThreadContext failed

### ISSUE THREAD

**Issue by illmouk** [pipliz/ColonySurvival#159]
they are saying GetThreadContexte failed and after a folder add to my stuff it a cras report folder named 2017-11-27_112620

[2017-11-27_112446.zip](https://github.com/pipliz/ColonySurvival/files/1506695/2017-11-27_112446.zip)

**Comment by pipliz** [comment]
Hi, previous people with this error had success when they added the game as an exception to their antivirus scanning. Can you try that? (assuming you're running anything that isn't windows default)

**Comment by illmouk** [comment]
i got windows defender

**Comment by illmouk** [comment]
i tried still not working

**Comment by pipliz** [comment]
Sorry, there's not a lot more I can do. It's an issue with the engine I'm using (Unity3D) which I can't change/fix.

If you need assistance getting a refund, let me know.

**Comment by illmouk** [comment]
i asked for a refund 
thx i played a little bit and it was fun :) thank you for your time

**Comment by illmouk** [comment]
welp they did not accept my refund

**Comment by illmouk** [comment]
this is the link to my account 
http://steamcommunity.com/id/-Zade-/

**Comment by illmouk** [comment]
i want you too help me to refund pls sir?

**Comment by illmouk** [comment]
this is the request reference HT-HYP7-7TQC-BVQ5

**Comment by Ateir** [comment]
Having the same issue 

"Fatal error in gc
GetThreadContext failed"

Surely there must be a way to fix this?

**Comment by pipliz** [comment]
@illmouk Sorry, I completely missed your comment. Is this still a thing? (I hope you get a mail or something from this...)

**Comment by pipliz** [comment]
More reports of the same: http://steamcommunity.com/app/366090/discussions/4/1621724915794537161/

**Comment by pipliz** [comment]
> The core problem is a problem with Unity3D, the engine the game is built in, which is a very rare 
issue but somehow it becomes common when some antivirus programs poke in the game.

My comment there.

It'll likely get fixed in a few months time when I upgrade the engine version, or possibly earlier if unity3d releases a patch fixing it (unlikely).

**Comment by Ateir** [comment]
Understood, to add to it I'm not running any external anti-virus program, and the game is whitelisted through Defender and Firewall

Also, adding crash reports here in case you can make some use of them



[Crash Reports (Colony Survival).zip](https://github.com/pipliz/ColonySurvival/files/1593450/Crash.Reports.Colony.Survival.zip)

**Comment by pipliz** [comment]
Late update to anyone googling for this; the anticheat program FaceIt seems to cause some incompatibility issues resulting in these crashes as well.

**Comment by pipliz** [comment]
Likely fixed in the next update (most recent unity version)
