### ISSUE TITLE
Game Crashed During Start

### ISSUE THREAD

**Issue by TyphoonNova** [pipliz/ColonySurvival#167]
Game simply crashed when I started it up after not playing for a month and then updating to the latest version (v0.4.5). Don't know what would have caused this, could have been a fluke for all I know: but, it could be something more. Crash report is attached. Have fun deciphering it.

[2017-12-21_192430.zip](https://github.com/pipliz/ColonySurvival/files/1581085/2017-12-21_192430.zip)

Update: Second instance of running the game(Directly after crash), loaded just fine: no crash.

**Comment by pipliz** [comment]
Seems to be an issue with steam being unable to load it's context. First one of those I've seen.

Glad to hear it ran correctly on the second try.

**Comment by Daniel-Read** [comment]
my Game did the same but I cant get it to work.
