### ISSUE TITLE
Feilds

### ISSUE THREAD

**Issue by halfweed** [pipliz/ColonySurvival#172]
Its not so much of a bug i think as it is just an over site. but as i am trying to place berry fields down.( n i haven't gotten north, south figured out but will use them with ex.) placing a 3x11 north to south i cant place the same 3x11 east and west. i dont know if this is intentional or just an over site. and i think a few of the other sizes have the same issue with it as well. Thank you for you time.

**Comment by pipliz** [comment]
Fixed in 0.5(.2?)
