### ISSUE TITLE
"Food usage 2" achievement doesn't work properly

### ISSUE THREAD

**Issue by TAQrinzAN** [pipliz/ColonySurvival#175]
"Food usage 2" achievement isn't unlocked when food usage reaches to 250.
It is unlocked when food usage reaches to 255.
![](https://user-images.githubusercontent.com/34472767/34455081-a3deca30-edba-11e7-9f2c-5dfcc7af99b4.png)

**Comment by pipliz** [comment]
Pretty much a steam thing, not a lot I can do :(
