### ISSUE TITLE
Sketchy multiplayer search

### ISSUE THREAD

**Issue by vishal-parameswaran** [pipliz/ColonySurvival#180]
Current Version : 0.5.0

Me and friend have tried setting up servers to play together, but we have not been able to find each others servers on the internet. It worked once, but after that it has just never worked.
We both have port-forwarded PC's, and are using the SteamOnline setting.
This is my log-file
[2018-01-09_15-04-14.txt](https://github.com/pipliz/ColonySurvival/files/1614772/2018-01-09_15-04-14.txt)

**Comment by pipliz** [comment]
Can you see if the steam builtin browser does show the game? In steam's main menu, go to view -> servers.

**Comment by vishal-parameswaran** [comment]
It never worked, even if I tried adding the server manually, it always said no servers found. I can find my server under LAN obviously.
