### ISSUE TITLE
Stockpile items jump around

### ISSUE THREAD

**Issue by Zsynh** [pipliz/ColonySurvival#187]
Heyo! Still loving this game so much, thanks for making such a fun thing. :)

One issue I'm having, especially once I have most inventory items in stock, is the items move around several times per second, making it nearly impossible to grab the item I want out of inventory. Would it be possible to introduce a bit of a delay to the inventory update process? Even just a second or two would completely solve the problem.

Thanks!

**Comment by pipliz** [comment]
Yeah it's a real problem 👍

**Comment by pipliz** [comment]
Fixed for 0.6.1
