### ISSUE TITLE
Suggestion - How Much Food is Being Produced Daily

### ISSUE THREAD

**Issue by Zsynh** [pipliz/ColonySurvival#188]
It would be super handy to know how much food I'm producing daily to make strategic planning easier. Thanks!

**Comment by Barklc** [comment]
I would add overall statics about all production occurring in the colony to help manage it.  An example is average amount of each resource collected or the number of an item made each day.

**Comment by pipliz** [comment]
Planned; overall statistics about all production/consumption!

**Comment by pipliz** [comment]
production/consumption stats are in for 0.9
