### ISSUE TITLE
Suggestion - Pathfinding Help

### ISSUE THREAD

**Issue by Zsynh** [pipliz/ColonySurvival#189]
Howdy again -

It would be really helpful to be able to click on a settler who can't path to his destination and have that destination highlighted. Right now, I have no idea what these guys need or where they want to go. 

![20180122144450_1](https://user-images.githubusercontent.com/439773/35248599-9d53d040-ff83-11e7-8a6e-2bdeac7483ec.jpg)
![20180122144450_1](https://user-images.githubusercontent.com/439773/35248615-a763a344-ff83-11e7-93af-7d5be6cf1320.jpg)

Thanks!

**Comment by pipliz** [comment]
Done - left-clicking an npc with the command tool will show the goal with 0.7.0
