### ISSUE TITLE
missing translations for things not translated

### ISSUE THREAD

**Issue by JBurlison** [pipliz/ColonySurvival#194]
https://github.com/JBurlison/Pandaros.Settlers/issues/21

If a translation does not exist it just shows the item name. in the example here, there is an English fallback, maybe it should aways fallback to English?

**Comment by Dorky106** [comment]
While a fallback to a degree would be nice, I feel that not having it also helps as well, as it shows the exact translation string that needs to be localized.  At which point a player can tell the devs/modder which string needs to be localized into what language.  Which is much easier to figure out what string from that than being told what item needs to be fixed into a set language.
But that is just my input on this.

**Comment by pipliz** [comment]
-Fixed modded locales falling back to the clients' en-US instead of the server one

Already had it fixed for 0.6 :)
