### ISSUE TITLE
the game crashed

### ISSUE THREAD

**Issue by bluesarkade** [pipliz/ColonySurvival#199]
When I launch the game, I've got this message : "The game crashed. The crash report folder named 2018-03-03_154034 next to game executable" and I can't play. Have you got a solution?
Thanks

**Comment by pipliz** [comment]
Can you upload said folder? There's more details in the files there. Hard to say anything without those details. Have you tried adding it to antivirus exceptions (if you're running any 3rd party antivirus program)?
