### ISSUE TITLE
World Saving issue.

### ISSUE THREAD

**Issue by JordanSchloemer** [pipliz/ColonySurvival#20]
I had just started a very extensive project including building a massive bridge and castle, with a little town beneath. I exited the game normally by exiting to the menu then closing out of the window, I shut down my computer soon after. When I loaded up the world this morning, everything had been reset to default including food and items. the number of colonists we're the same around 34 but my food went from 2000 to 300. I was also put into siege mode even though I had placed my banner. I was spawned very far away from where I exited from, in fact, I can't find my colony. While searching for my colony I saw a very strange rock formation coming out of a mounting just a 10x10 square of rock protruding from the mountain. Please look into this bug as it it very game breaking.

**Comment by pipliz** [comment]
Hi, thanks for the report. It's quite problematic to find out what is causing it. You only notice it when you start the world up again, and by then the log files are gone.

Is your game placed in the program files map? (default steam installation folder).

Did you shut down your computer normally? (i.e, use the interface instead of holding the physical button)

**Comment by JordanSchloemer** [comment]
I can't check where its installed right now but I do believe its installed
normally, when I shut off NY computer i hit the physical button, and it
shuts down as if I hit the digital button

On Jul 11, 2017 2:42 AM, "Pipliz" <notifications@github.com> wrote:

Hi, thanks for the report. It's quite problematic to find out what is
causing it. You only notice it when you start the world up again, and by
then the log files are gone.

Is your game placed in the program files map? (default steam installation
folder).

Did you shut down your computer normally? (i.e, use the interface instead
of holding the physical button)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pipliz/ColonySurvival/issues/20#issuecomment-314361966>,
or mute the thread

**Comment by JordanSchloemer** [comment]
I also experienced world generation issues after this, similar to running
out of storage when playing Minecraft, but I have about 15gb of storage left

**Comment by pipliz** [comment]
"While searching for my colony I saw a very strange rock formation coming out of a mounting just a 10x10 square of rock protruding from the mountain."

I've seen this as well, it seems to be a client thing; reloading seems to fix it.

If this keeps happening, can you try running as administrator?

Also, if you're running an antivirus program (that isn't the default windows 10 one), you can try adding the server to the exceptions of it.

Sorry for the slower response time.

**Comment by JordanSchloemer** [comment]
No worries at all, I only have windows defender on. Do you know what causes
all if my items to be reset to the default items (the items and food you
get when you create a new world)?
Thank you,

**Comment by pipliz** [comment]
The resetting happens when the server for some reason fails to write or load the player-related savegame file. This includes position, inventory, stockpile, health & crafting limits.

**Comment by pipliz** [comment]
Seems we have found the main cause of this issue, it should be fixed for 0.3.0
