### ISSUE TITLE
Issue in APIProvider for CraftingJobBase.GetRecipeLocation

### ISSUE THREAD

**Issue by Barklc** [pipliz/ColonySurvival#201]
Let me start with telling you how great it is the level of access you provide for modding this early in the dev process.

I recently created a mod that added a work table.  I set the GetRecipeLocation to point to an empty JSON file and everything works fine with me entering the recipes for the work table myself.  If I put any recipes in the JSON file pointed to by the GetRecipeLocation, I get blank rows in the work table equal to the number of recipes in the JSON.

**Comment by pipliz** [comment]
Does it throw any errors or warnings into the server log/console? If not, can you try running the game on the debug branch on steam (via the games' properties in steam)? It should be the same patch as the default branch but has added checks, warnings & debugging data.

**Comment by Barklc** [comment]
The following should up in the log file when the JSON is read in by GetRecipeLocation.  When I add it through code to my new workbench these do not show up.

(Filename: C:/Unity/ColonySurvival/ServerProject/Assets/Recipes/Recipe.cs Line: 96)

Amount <= 0 for a result of FloorTile
Assertion failed. Value was True
Expected: False
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogAssertion(Object)
UnityEngine.Assertions.Assert:Fail(String, String)
UnityEngine.Assertions.Assert:IsFalse(Boolean, String)
Recipe:AssertIsValidRecipe() (at C:\Unity\ColonySurvival\ServerProject\Assets\Recipes\Recipe.cs:97)
Recipe:.ctor(JSONNode) (at C:\Unity\ColonySurvival\ServerProject\Assets\Recipes\Recipe.cs:42)
Recipe:LoadRecipes(String) (at C:\Unity\ColonySurvival\ServerProject\Assets\Recipes\Recipe.cs:266)
Pipliz.Mods.APIProvider.Jobs.CraftingJobBase:GetCraftingLimitsRecipes() (at c:\Unity\ColonySurvival\Build\gamedata\mods\Pipliz\APIProvider\src\Jobs\CraftingJobBase.cs:172)
Pipliz.Mods.APIProvider.Jobs.BlockJobManagerTracker:RegisterRecipes() (at c:\Unity\ColonySurvival\Build\gamedata\mods\Pipliz\APIProvider\src\Jobs\BlockJobManagerTracker.cs:136)
Pipliz.Mods.APIProvider.ModEntries:AfterItemTypesDefined() (at c:\Unity\ColonySurvival\Build\gamedata\mods\Pipliz\APIProvider\src\ModEntries.cs:43)
ModLoader:TriggerCallbacks(EModCallbackType) (at C:\Unity\ColonySurvival\ServerProject\Assets\Shared\ModLoader.cs:429)
ServerManager:Initialize(ServerOptions) (at C:\Unity\ColonySurvival\ServerProject\Assets\ServerManager.cs:327)
UnityWrapper:Start() (at C:\Unity\ColonySurvival\ServerProject\Assets\UnityWrapper.cs:127)
 
(Filename: C:/Unity/ColonySurvival/ServerProject/Assets/Recipes/Recipe.cs Line: 97)

Type == 0 for a requirement of FloorTile
Assertion failed. Value was True
Expected: False
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogAssertion(Object)
UnityEngine.Assertions.Assert:Fail(String, String)
UnityEngine.Assertions.Assert:IsFalse(Boolean, String)
Recipe:AssertIsValidRecipe() (at C:\Unity\ColonySurvival\ServerProject\Assets\Recipes\Recipe.cs:98)
Recipe:.ctor(JSONNode) (at C:\Unity\ColonySurvival\ServerProject\Assets\Recipes\Recipe.cs:42)
Recipe:LoadRecipes(String) (at C:\Unity\ColonySurvival\ServerProject\Assets\Recipes\Recipe.cs:266)
Pipliz.Mods.APIProvider.Jobs.CraftingJobBase:GetCraftingLimitsRecipes() (at c:\Unity\ColonySurvival\Build\gamedata\mods\Pipliz\APIProvider\src\Jobs\CraftingJobBase.cs:172)
Pipliz.Mods.APIProvider.Jobs.BlockJobManagerTracker:RegisterRecipes() (at c:\Unity\ColonySurvival\Build\gamedata\mods\Pipliz\APIProvider\src\Jobs\BlockJobManagerTracker.cs:136)
Pipliz.Mods.APIProvider.ModEntries:AfterItemTypesDefined() (at c:\Unity\ColonySurvival\Build\gamedata\mods\Pipliz\APIProvider\src\ModEntries.cs:43)
ModLoader:TriggerCallbacks(EModCallbackType) (at C:\Unity\ColonySurvival\ServerProject\Assets\Shared\ModLoader.cs:429)
ServerManager:Initialize(ServerOptions) (at C:\Unity\ColonySurvival\ServerProject\Assets\ServerManager.cs:327)
UnityWrapper:Start() (at C:\Unity\ColonySurvival\ServerProject\Assets\UnityWrapper.cs:127)
 
(Filename: C:/Unity/ColonySurvival/ServerProject/Assets/Recipes/Recipe.cs Line: 98)

Type == 0 for a result of FloorTile
Assertion failed. Value was True
Expected: False
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogAssertion(Object)
UnityEngine.Assertions.Assert:Fail(String, String)
UnityEngine.Assertions.Assert:IsFalse(Boolean, String)
Recipe:AssertIsValidRecipe() (at C:\Unity\ColonySurvival\ServerProject\Assets\Recipes\Recipe.cs:99)
Recipe:.ctor(JSONNode) (at C:\Unity\ColonySurvival\ServerProject\Assets\Recipes\Recipe.cs:42)
Recipe:LoadRecipes(String) (at C:\Unity\ColonySurvival\ServerProject\Assets\Recipes\Recipe.cs:266)
Pipliz.Mods.APIProvider.Jobs.CraftingJobBase:GetCraftingLimitsRecipes() (at c:\Unity\ColonySurvival\Build\gamedata\mods\Pipliz\APIProvider\src\Jobs\CraftingJobBase.cs:172)
Pipliz.Mods.APIProvider.Jobs.BlockJobManagerTracker:RegisterRecipes() (at c:\Unity\ColonySurvival\Build\gamedata\mods\Pipliz\APIProvider\src\Jobs\BlockJobManagerTracker.cs:136)
Pipliz.Mods.APIProvider.ModEntries:AfterItemTypesDefined() (at c:\Unity\ColonySurvival\Build\gamedata\mods\Pipliz\APIProvider\src\ModEntries.cs:43)
ModLoader:TriggerCallbacks(EModCallbackType) (at C:\Unity\ColonySurvival\ServerProject\Assets\Shared\ModLoader.cs:429)
ServerManager:Initialize(ServerOptions) (at C:\Unity\ColonySurvival\ServerProject\Assets\ServerManager.cs:327)
UnityWrapper:Start() (at C:\Unity\ColonySurvival\ServerProject\Assets\UnityWrapper.cs:127)

**Comment by pipliz** [comment]
It likely means the recipe format doesn't follow the format used in mods/Pipliz/BaseGame/gamedata/crafting.json & it's friends.

Like:
```
{
	"name" : "pipliz.crafter.slingtemperate",
	"results":[{"type":"sling"}],
	"requires":[{"type":"leavestemperate"}],
	"defaultLimit" : 5,
	"defaultPriority" : 100
},
```

**Comment by Barklc** [comment]
I embarrassed to say that was the problem.  I was not added the namespace in the json file.
