### ISSUE TITLE
Pathfinding for colonists and auto siegemode

### ISSUE THREAD

**Issue by WolfxofxDemons** [pipliz/ColonySurvival#21]
ive notice that when you dig underground or have too many colonists you start having pathfinding issues where the colonists have a clear path to work station or bed but just cant move? also when this happens sometimes at night the banner goes into siege mode on its own and zombies are able to spawn and make their way to flag. I lost 2 colonies this way. ive double checked the opening since I was on a multiplayer server for these incase of griefers but no one else was near me since I built in a nice valley. can attach pictures of area if you would like.

**Comment by pipliz** [comment]
What kind of specifications does your pc have? (CPU / GPU)

Also, did the zombies glitch around as well? (indication of the server being under heavy load)

**Comment by WolfxofxDemons** [comment]
I have an intel core i7. memory is also good and I have a Nivida GeForce graphics card idk exact model but since I'm using a laptop not the best.

And no zombies were fine. They skipped a few times but that was mostly cause we had a lot of people on server at same time. So I'm sure that didn't have much to do with it.

~Akira Kailos

On Jul 12, 2017, at 10:43 AM, Pipliz <notifications@github.com<mailto:notifications@github.com>> wrote:


What kind of specifications does your pc have? (CPU / GPU)

Also, did the zombies glitch around as well? (indication of the server being under heavy load)

**Comment by pipliz** [comment]
Alright. Can you check if the same issue exists in singleplayer? It's quite hard to explain a server-side issue without the server owner =/

**Comment by WolfxofxDemons** [comment]
Sure I'll check

~Akira Kailos

On Jul 15, 2017, at 6:51 AM, Pipliz <notifications@github.com<mailto:notifications@github.com>> wrote:


Alright. Can you check if the same issue exists in singleplayer? It's quite hard to explain a server-side issue without the server owner =/

**Comment by WolfxofxDemons** [comment]
Ok so I built on a single player but so far haven't been able to reproduce so it might just be a multiplayer thing or something that was fixed with last update.

~Akira Kailos

On Jul 15, 2017, at 6:51 AM, Pipliz <notifications@github.com<mailto:notifications@github.com>> wrote:


Alright. Can you check if the same issue exists in singleplayer? It's quite hard to explain a server-side issue without the server owner =/

**Comment by pipliz** [comment]
Alright, great to hear. If it comes back somewhere, please report it.
