### ISSUE TITLE
People connecting to the server with whitelisting enabled 

### ISSUE THREAD

**Issue by ChiefJord** [pipliz/ColonySurvival#210]
My current setup:
Ubuntu 17.10 server running the latest version of colony survival with whitelisted steamIDs

There has been a few times where a steam user would be able to join my server who are not whitelisted. They are then kicked 30 mins later for not being whitelisted. 

From the logs, it seems that someone connected at 2018-04-06  15-37-13 and then got kicked 2018-04-06 16-04-54 for not being on the whitelist. 

From my perspective it looks like either they found a way to delay/stop the check allowing them to connect. 

Here are the logs.

> [2018-04-06_15-37-13][Log]:Connected player: Steam: *********** (previously named )

> [2018-04-06_15-37-13][Log]:[SteamAPI] Authentication ticket of ********* deemed OK

> [2018-04-06_16-03-48][Log]:Disconnected player: Steam: *********** (named ********)

> [2018-04-06_16-04-49][Log]:[SteamAPI] Refusing connection from account *********, reason NotOnWhiteList

This is all from the same account.

**Comment by pipliz** [comment]
Thanks for reporting, I'll take a look at it. 0.6.1 should get a new/better server browser and passworded servers, so I can probably fix this while working on that.

**Comment by pipliz** [comment]
the passworded option is there for 0.6.1, with a new server browser and improve connection/authentication logic - hopefully it'll prevent this issue from happening again.
