### ISSUE TITLE
game wont start

### ISSUE THREAD

**Issue by lewisgamehunter** [pipliz/ColonySurvival#218]
can you help me i just get an error message and it says send to a dev

[error.log](https://github.com/pipliz/ColonySurvival/files/1978029/error.log)
[output_log.txt](https://github.com/pipliz/ColonySurvival/files/1978030/output_log.txt)

**Comment by pipliz** [comment]
Sorry to say, but it looks like your computer does not reach the minimum hardware specifications required.
If you're confident that your computer does meet them (most computers from the last ~5 years should reach it) I'd recommend reinstalling the graphics drivers for your video card.
