### ISSUE TITLE
Gray screen on main menu

### ISSUE THREAD

**Issue by ThegdogTwitch** [pipliz/ColonySurvival#22]
https://gyazo.com/5398f4055198aa1fc7ac2d236f06833c pitcure of whats going on.  this is happening when i start almost instantly.  i see sometime split secounds of the main menu.  im willing to talk over a voice app if you cant help me solve this.  voice apps i use are discord and TS3.  pleas help me.

**Comment by pipliz** [comment]
Hi, sorry for the slower response.

Can you confirm if your pc meets the minimum requirements? (some form of dedicated gpu from the past 5-ish years)?

Also adding the output_log.txt from "colony survival/colonyclient_data/" would be appreciated.

**Comment by ThegdogTwitch** [comment]
yes, brand new, an i7 6700k 4 core cpu and a Msi 1070 for my graphics with 16gb ram.  
[DxDiag.txt](https://github.com/pipliz/ColonySurvival/files/1150733/DxDiag.txt)

**Comment by ThegdogTwitch** [comment]
the dxdiag is a file from the windows feature dxdiag displaying all my pc specs.

**Comment by pipliz** [comment]
Yes that definitely meets minimum requirements. I've seen similar issues with other gtx 10** users for some reason. Can you try launching the game with the following launch arguments (in the game properties in the steam library)

-force-d3d12

or

-force-glcore

This will override the default directX 11 to directX 12 or openGL. The game does seem to crash when you exit with these arguments, but it's after all game code has been run, so it does not impact saving etc.

It'd be great to hear if this helped or not.

**Comment by ThegdogTwitch** [comment]
how would i add this arguments?  i know usually in the target field of properties but in the properties for colony survial its jsut a URL and shortcut Key 
![image](https://user-images.githubusercontent.com/30161865/28346040-4f835608-6bfc-11e7-8b22-0a702d9a6624.png)

**Comment by ThegdogTwitch** [comment]
how would i add these arguments?  i know to usally add it in the target feild of properties when on the shortcut but this is all i see
![image](https://user-images.githubusercontent.com/30161865/28346082-7d2511dc-6bfc-11e7-89f8-1d14367a08bd.png)

**Comment by ThegdogTwitch** [comment]
NVM, just remade the shortcut its now fixed

**Comment by ThegdogTwitch** [comment]
and looks like -force-d3d12 did fix it.  for future reference can you tell me what thats doing?

**Comment by pipliz** [comment]
There seems to be a bug in unity with certain gtx 10** cards with directX 11. The overloads use openGL (-force-glcore) or directX 12 (-force-d3d12). Sadly I can't provide an option ingame for it due to the way unity does things.

**Comment by ThegdogTwitch** [comment]
Ah ok.  Well thank you for the help.  And ik unity, it can be stupid at times XD i do android apps on it
