### ISSUE TITLE
Research screen and inventory scrolling bug

### ISSUE THREAD

**Issue by phraggers** [pipliz/ColonySurvival#220]
Since the latest update, when I click the scroll-bar in the research or inventory screen, the left hand panel will scroll down to the bottom (as if I was holding a scroll-down arrow in a web browser for example) until I click empty space between icons in the left panel. Anyone else have this bug, or just me?

**Comment by phraggers** [comment]
also note that it doesn't happen 100% of the time. Usually when ever I click "start research"

**Comment by pipliz** [comment]
So you click it once (not holding) and then it slowly starts scrolling down? Very strange. First I've heard of it, and I have no idea how that could happen...

**Comment by phraggers** [comment]
Exactly. If nobody else has this, it's very possible it's something my end. I'll have to do some more experimenting when I have time; I'm quite busy at work at the moment but am keen to help if it's a possible bug. I'm not very familiar with Unity, so I'm not sure what may be a cause: I have 3 1080p monitors, two side by side and one aligned centre above. I also have many peripherals attached, eg a couple of external sound cards, steering wheel, PS4 controller, etc, and I have a few third party desktop addons. Any tips on where I should start? :)
If I get any clues I'll let you know!

edit: Is there any other input source that can affect these screens/panels other than mouse input?

**Comment by pipliz** [comment]
It is plausible that it's some semi-automatic controller support from unity picking up inputs from your ps4 controller or steering wheel to try and control the selected item (= the scroll bar). Can you try decoupling them and see if it fixes it? I haven't configured a deadzone setting in unity, it may be that it's picking up some slightly-off-neutral values and thinking you're using one of the joy sticks.

**Comment by phraggers** [comment]
Mysteriously this issue has since ceased, you can probably close this, especially if no-one else has reported it. Weird!
edit: just noticed I have to close it haha
edit2: And I couldn't get any response from my controllers in-game.
