### ISSUE TITLE
Bread Crate seems to do nothing.

### ISSUE THREAD

**Issue by Planet-BBob** [pipliz/ColonySurvival#225]
What is the purpose of the Bread Crate (knife & fork on crate)? I can place them near my baker, but they are never used by the colonists, nor do they interact with the user. I would like it if it could be selected, then right click to gain access to a sub-menu to store/remove excess bread from it.   I would be nice to store up to 500 bread in a crate.  I also do not see a drop in Bread count when I place the Bread Crate. Thoughts?

**Comment by Planet-BBob** [comment]
I have steam set to update as needed, so I should have the latest released update.

**Comment by pipliz** [comment]
The purpose is simply to store some food in a physical block, for emergency use (if you recruit too many colonists / don't make enough food) or to 'trade' it with other people (optionally using the construction jobs).

They do not work as a crate like the normal crate. We're aware this is somewhat confusing.
