### ISSUE TITLE
Can existing Mindcraft Designs from XBox 360 be used in Colony Survival?

### ISSUE THREAD

**Issue by Planet-BBob** [pipliz/ColonySurvival#226]
Is there a way to use an existing Mindcraft Design, all files, from XBox 360 in Colony Survival?

If not, is there a way to save a map in Mindcraft and utilize it in Colony Survival?

How about a public blueprint store where users can upload designs, and download and use in their own worlds?

**Comment by pipliz** [comment]
There is no simple way to use voxel designs from other games/programs in our game. You'll have to write a converter yourself.

We do plan to eventually add steam workshop support, blueprints/scenarios/saves/mods may all be available on there by then.

**Comment by Planet-BBob** [comment]
ugh, thanks.  I see the regions are binary, and thus would require an API or good definition to do that.  For now I'll wait, thanks.
