### ISSUE TITLE
Suggestion: Berries

### ISSUE THREAD

**Issue by Planet-BBob** [pipliz/ColonySurvival#227]
It would be interesting to see another station of a cook that can use items to make other food from bread and berries.  Perhaps Pancakes, Maple Syrup from Specifically Maple Trees, Jelly/Jam from Berries, to name some ideas.   Obviously Forester would need to discern Maple Trees from others, and perhaps you could have another colonist that collects the maple syrup from a maple tree.  Jams/Jelly could be sold to other players?  Same with Maple Syrup?  Perhaps you could even go as far as a player building a restaurant with the cook in it, and a store?  Just spewing ideas.
PS: Love the game.

**Comment by pipliz** [comment]
There's more recipes now :)
