### ISSUE TITLE
Suggestion: guard detail info

### ISSUE THREAD

**Issue by Planet-BBob** [pipliz/ColonySurvival#232]
If would be great if there was a way to display a list of all guards, their x,y,z coords, and a count of how many shots each have taken.   It would greatly help reduce the overkill of guards and help better distribute them around the complex.   I'm built in to the side of a mountain and have to put guards around to cover the dusk and dawn time-frames, otherwise I get straggler monsters killing my field workers.

**Comment by pipliz** [comment]
This is probably something you'll have to keep doing manually :) Maybe 0.9 traps can help, though a minor stretch
