### ISSUE TITLE
Suggestion: Transport coordinates

### ISSUE THREAD

**Issue by Planet-BBob** [pipliz/ColonySurvival#233]
It would be really great, especially on a multi-player server, if there was a command like /setlocation or /transport that would allow you to put in x,y,z coordinate location and it would take you there.  Otherwise it is near impossible to find another player's build-out in a vast world.  It would obviously have to auto-correct for placing you in the air too high where you would die when you fell, or inside solid rock, etc.
-Thanks.

**Comment by pipliz** [comment]
`/teleport {x} {y} {z}` exists. Though it doesn't auto-correct, and is obviously a cheat
