### ISSUE TITLE
Game crashes and single player will not load

### ISSUE THREAD

**Issue by Royalcasino12** [pipliz/ColonySurvival#234]
[error.log](https://github.com/pipliz/ColonySurvival/files/2095261/error.log)
I am experiencing some issues with trying to load single player when ever I launch the new world it will stop at 60 and say failed to connect to network or something and crash I have tried uninstalling the game and reinstalling it still no luck
There is the error log I am getting
and here is the crash folder 

[error.log](https://github.com/pipliz/ColonySurvival/files/2095855/error.log)
[output_log.txt](https://github.com/pipliz/ColonySurvival/files/2095856/output_log.txt)

**Comment by pipliz** [comment]
Hi, thanks for reporting the problem.

There's a known incompatibility with the following programs: Avast (antivirus), FaceIt (anticheat/matchmaking) and Razer Synapse. If you are running any of those, can you try shutting them down and see if that fixes the problem?

If not and you are running antivirus software other then windows defender, can you see if adding the game to to it's exceptions list helps?

**Comment by Royalcasino12** [comment]
Unfortunately it has not, but the odd thing is if I first join a multiplayer server then load the single player it works not sure why?

**Comment by Royalcasino12** [comment]
Jackps9 help me figure out the problem I needed to uninstall face anti cheat that was the issue, I thought if I had closed it wouldn't run but it still caused an issue but now the game works great!

**Comment by pipliz** [comment]
This crash issue is likely fixed in the next update
