### ISSUE TITLE
Torches. They don't work.

### ISSUE THREAD

**Issue by NightHag** [pipliz/ColonySurvival#24]
Windows 10, new laptop, not very powerful. Singleplayer, don't know about singleplayer.

Torches
A) don't produce light
B) don't have a physical body. It's like a hollow torche model. If you break a block under it, it doest't go away, but continues to float, and where is no way to destroy it.
C) you can place an infinite amout of these bugged torches, no matter how many you have in the inventory. They just won't end.

Restarting the game made all of the broken torches go away and fixed the problem.

P.S Luv your game <3

[output_log.txt](https://github.com/pipliz/ColonySurvival/files/1154044/output_log.txt)

**Comment by pipliz** [comment]
Well that's a new one. Thanks for the report. The log you attached doesn't have any errors in it though, are you sure it's one from a game launch where this happened? I can imagine this being a one time thing.
