### ISSUE TITLE
Construction Job Failing Over Long Distances

### ISSUE THREAD

**Issue by susanbrindle** [pipliz/ColonySurvival#240]
I've experienced this bug with both diggers and builders when working on very long designations. (Carving a 2x10x10,000 road, for example.) Construction jobs deliver a "failed" message when they try to interact with blocks more than a few hundred tiles away. Upon walking over, construction resumes. 

I'd guess that it's failing to interact with blocks that aren't loaded because they're too far away from the player or another active entity.

**Comment by pipliz** [comment]
Correct @ the cause. It'll probably remain that way though
