### ISSUE TITLE
Game crash at random

### ISSUE THREAD

**Issue by cccarrow** [pipliz/ColonySurvival#243]
[error.log](https://github.com/pipliz/ColonySurvival/files/2562993/error.log)
[output_log.txt](https://github.com/pipliz/ColonySurvival/files/2562995/output_log.txt)

Whenever the game crashes, all sound output from all sources is broken until the computer is restarted

**Comment by pipliz** [comment]
Looks like a driver/hardware issue more than game issue to be honest.

It's returning a 
>D3D11: Failed to create RenderTexture (1360 x 768 fmt 19 aa 1), error 0x887a0005 

Which is associated with gpu device removal/rebooting
