### ISSUE TITLE
Oops! The game crashed

### ISSUE THREAD

**Issue by p0kemonZ** [pipliz/ColonySurvival#248]
I just bought the game, but it wont start. Here's the most recent crash folder. Any tips?

[error.log](https://github.com/pipliz/ColonySurvival/files/2717452/error.log)
[output_log.txt](https://github.com/pipliz/ColonySurvival/files/2717453/output_log.txt)

**Comment by pipliz** [comment]
See if adding the game to AVG's scanning exceptions helps. It's the most common cause of these crashes at the moment (anti virus software injects some code into the engine, which messes with things - hopefully it's fixed for the next patch)

**Comment by digdog5544** [comment]
Hello, I was wondering if this issue was ever resolved?  I bought this game to play with my son and am running into the same error.  I've excluded the game files from AV (Norton).  
[error.log](https://github.com/pipliz/ColonySurvival/files/2897340/error.log)
[output_log.txt](https://github.com/pipliz/ColonySurvival/files/2897341/output_log.txt)

**Comment by p0kemonZ** [comment]
No, sorry. I’ve given up on the game for now, hoping they’ll resolve the issue in time. I’d reccomend posting it for the devs, and they’ll probably help you figure it out. I didn’t bother to much because I started playing other games, such as Atlas.

Sent from my iPhone

On 23 Feb 2019, at 23:36, digdog5544 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, I was wondering if this issue was ever resolved? I bought this game to play with my son and am running into the same error. I've excluded the game files from AV (Norton).
error.log<https://github.com/pipliz/ColonySurvival/files/2897340/error.log>
output_log.txt<https://github.com/pipliz/ColonySurvival/files/2897341/output_log.txt>

**Comment by pipliz** [comment]
It is quite likely resolved with version 0.7, as it updates the version of Unity3D used (from 5.6 to 2018.4). The old version used was the primary cause of this error.
