### ISSUE TITLE
Suggestion: Production Tab

### ISSUE THREAD

**Issue by Mazriq** [pipliz/ColonySurvival#250]
Just as someone recommended for food production per day. Have a quick tab assigned to a key that brings up 'Raw Resource Production'. That is How much Copper, Tin, Gold etc. is being mined per day. How much Wood is being chopped per day, and how much berries/herbs are being picked per day. 

If implementation is easy, you could do a whole table popup for every resource and the production value per day. eg ingots.

**Comment by pipliz** [comment]
Should be in for 0.9; production/consumption graphs for pretty much all the items, besides the "level in stockpile" graphs that existed before this
