### ISSUE TITLE
Bug Reports: Invisible Banner

### ISSUE THREAD

**Issue by Mazriq** [pipliz/ColonySurvival#252]
While playing with some friends on private server, one of our flags glitched out and turned invisible during a server restart. Siege mode was not activated but colonists could be spawned remotely. Breaking the blocks underneath where it used to be didn't help either. Maybe being able to break the flag remotely or replacing it to override the original position would help?

**Comment by pipliz** [comment]
Shouldn't be possible with 0.7 anymore
