### ISSUE TITLE
[Suggestion] Right click on a berry bush to get berries!

### ISSUE THREAD

**Issue by JBurlison** [pipliz/ColonySurvival#255]
it does not have to be a 100% chance but maybe like a 70% to get 1 and a 20% to get 2. Maybe there is a internal cooldown of 1 pull per second. Plus it will give people a way back after wiping. Just 10 - 15 minutes of manual labor can get your colony going again/

**Comment by pipliz** [comment]
Not sure if 10 mins of berry labor is the way, but added wipe-recovery to #321
