### ISSUE TITLE
Suggestion: Automated doors

### ISSUE THREAD

**Issue by Gabbleducky** [pipliz/ColonySurvival#262]
It would be really helpful to have automated doors, I have currently got several farms outside my walls as I would prefer not to have to build multi-storey farms, and I currently have to go around knocking holes in my walls every morning to let my farmers out, and fill them in every evening.

My suggestion would be to have a door block (2 blocks high) and to create a new job - gatekeeper - who would go to their door when the sun rises and open it, and close it when the sun goes down (or slightly after, to allow the outside the walls to get in)

**Comment by pipliz** [comment]
Added to #320 but it's a bit complicated
