### ISSUE TITLE
Calorie use/day hits 0 randomly causing mass starvation.

### ISSUE THREAD

**Issue by biouxtai** [pipliz/ColonySurvival#274]
When my population reaches over 90, after a while, my colonists will stand at the grocery table with their progress bar continuously filling up and starting over until they eventually die of starvation. In the space of about 5 minutes I recycled to a whole new set of 103 colonists as the original group got up in waves to go stand at the table and die.  This has been happening pretty regularly now.

**Comment by biouxtai** [comment]
After about 2 minutes or so, if I am within the colony, calorie use goes back to normal and everyone is fine until the nexy cycle of this.

**Comment by biouxtai** [comment]
got a pic of it.
![colonysurvival](https://user-images.githubusercontent.com/897029/62801060-dc087e80-bab2-11e9-96f1-0c23c7489751.png)

**Comment by Khanx** [comment]
Check your happiness sliders...

**Comment by biouxtai** [comment]
Happiness usage is disabled.

I think I figured it out. I had a ton of food, but the allocations were not correct for the types I had.

I think more info regarding this event is necessary to guide the player.

if I have 200k food and most is bread, but bread is only 5% of the calories, or the food allocation I have is all red, I may not know why they are starving.

Without looking at the grocery table, as a new player, I will not know what is going on.

Thanks

**Comment by pipliz** [comment]
I think this is 'fixed' for 0.9, with a decent overhaul of the food-related mechanics & UI
