### ISSUE TITLE
Completed science button status not changing

### ISSUE THREAD

**Issue by jjedlicka** [pipliz/ColonySurvival#295]
I could not complete my science.  Everything is done and ready, but the button never changed from "cancel" to "Complete"  I have restarted my game several times and the problem persists.

I am updated to the latest version (0.7.4).  The game was initially created in the previous version (0.7.3).

I am researching the Matchlock Gun.  everything is done, 25/25.  I did accidentally cancel when I had 24/25 on everything.  I don't know if that is what is causing this issue now.

I am not sure what other info you need.  Let me know and I will try to provide it.

**Comment by pipliz** [comment]
Way late reaction, sorry for that. It's been a year. It could be one of the cases where it's "24.9/25" and rounding up to 25/25. Either way, this shouldn't be a problem anymore with the way science works for 0.9 (not released yet)
