### ISSUE TITLE
Monsters spawn inside my walls

### ISSUE THREAD

**Issue by karlonist** [pipliz/ColonySurvival#32]
Monsters will spawn in this location and i cant figure out why. I don't know how the spawning exactly works but i don't think zombies should spawn inside my colony. i have had to not only set up archers at the entrance to my colony but archers scattered around the inside and i still get 1-5 deaths a night. Sorry for the picture quality i had to cut out personal parts of it hope you understand.

![untitled](https://user-images.githubusercontent.com/30361152/28487547-197bd8f4-6ed2-11e7-9909-e0363792feb4.png)

PS love your work with this game cant wait for future updates

**Comment by pipliz** [comment]
Currently there is a 'safe area' around the banner, outside of which the monsters spawn. So at the moment it is a bit annoying to make larger than 150x150 (or so) colonies.

We're planning on adding a kind of secondary banners or other ways of enlarging this area in the future.

**Comment by karlonist** [comment]
this was 20 blocks away from my flag

**Comment by pipliz** [comment]
Is it possible that your walled area extends beyond this 75m radius from the banner, and the zombies spawned there and walked over?

**Comment by karlonist** [comment]
no they I will be standing there every night to kill them with a bow as exactly when night time hits they will just spawn and I have tried everything (removing the banner and placing it right where they spawn, placing tree/wheat/berry farms on top) I ended up just going and making a new base about 100 blocks away and I haven't had troubles there but please fix

I would hate for this to happen to someone else as for almost 50 hours I was just looking through my base trying to see where they were spawning/coming from but I couldn't find it and then I just saw them spawn mid base and I was like yea that's legit

**Comment by pipliz** [comment]
#63
