### ISSUE TITLE
Safe Zone Glitching out.

### ISSUE THREAD

**Issue by Itswolfcity811** [pipliz/ColonySurvival#355]
In my new world of Colony Survival when I look at the banner tool and place a block on the edge of my safe zone it looks like I placed that block just outside of the safe zone, but when I put a block one block in it works fine. I also counted too many blocks.

**Comment by RadekPelikan** [comment]
### Exactly

The rendering of danger zone breaks on and above the level of the placed flag. It's sometimes confusing where do zombies spawn are where not.

The crate block is the level where the flag is placed
![image](https://github.com/pipliz/ColonySurvival/assets/79970400/3ae8c3af-cac3-4c9f-8a27-84c262386c44)

**Comment by pipliz** [comment]
Has since been fixed
