### ISSUE TITLE
Getting "Stuck" on blocks

### ISSUE THREAD

**Issue by Sharky10599** [pipliz/ColonySurvival#50]
When I'm just walking around on 1 wide walls, or pathways (with holes either side) I randomly get stuck on them. If I'm just holding down w, it won't let me continue and sometimes it pushes me off to the left or right. I've noticed that I can jump to temporarily solve it, but it is quite frequent and very irritating.

I've only played on a LAN Server with a friend and haven't tried out single player to see it if the problem is there as well, so it might only be to do with the server.

**Comment by pipliz** [comment]
Thanks for the report. We are aware of the issue and are planning a fix. It may make its way into the next patch, but I'm not sure.

**Comment by pipliz** [comment]
Part of #62
