### ISSUE TITLE
Add FPS/Server Tick Rate to graphing

### ISSUE THREAD

**Issue by tommykent1210** [pipliz/ColonySurvival#53]
We have no way (numerically) to see if lag is occurring - even if you just take mean time between 10 ticks or SOMETHING to give an idea of if the server itself is struggling!

**Comment by pipliz** [comment]
You'll have to do with either any fps counter program or the frametime graph.

Though, I've just changed the frametime graph a bit. A maxed graph meant >33 ms frametime (<30 fps), I've changed it to >100 ms (<10 fps). Servers probably shouldn't be below ~10 fps anyway.

**Comment by tommykent1210** [comment]
Yeah, it'd just be nice to have some kind of number, as opposed to just a a graph (which is hard to understand)
