### ISSUE TITLE
The Lost Banner Bug

### ISSUE THREAD

**Issue by Dorky106** [pipliz/ColonySurvival#54]
So someone on the Meta-Eco server went to move their banner and the server still registered the banner as placed. When anyone went to their base the banner could not be seen and blocks could be placed where the banner file said the banner was located.
This issue has happened twice on the server so far.

**Comment by pipliz** [comment]
This probably caused an error on either the client or the server. It's hard to do anything about it without the error.

**Comment by pipliz** [comment]
#63
