### ISSUE TITLE
Visualising chunk boundaries

### ISSUE THREAD

**Issue by tommykent1210** [pipliz/ColonySurvival#55]
It would be nice to be able to see chunk boundaries :)

**Comment by pipliz** [comment]
How do you propose to see them?

**Comment by tommykent1210** [comment]
Minecraft style, just a translucent plane that runs down chunk boundaries.

![def11af2a10a616f2e80ca295225e76b](https://user-images.githubusercontent.com/1753032/28755783-1980c114-755a-11e7-83e1-493717c5da8c.png)

**Comment by pipliz** [comment]
Not anytime soon :)
