### ISSUE TITLE
Fonts are a bit weird when bolt/italic

### ISSUE THREAD

**Issue by tommykent1210** [pipliz/ColonySurvival#56]
When writing a mod, that allows for further chat colours, it appears as though chat fonts when made bold are a little odd. The bold font appears to be quite squashed?

![fonts](https://user-images.githubusercontent.com/1753032/28754630-bd11c702-7540-11e7-9ca4-3e85af8be502.PNG)

**Comment by pipliz** [comment]
Interesting. It almost looks like it fallbacks to another font.

I'll have to take a look sometime :)

**Comment by tommykent1210** [comment]
:P Yes it appears so xD
