### ISSUE TITLE
fields not growing/out of sync error on console

### ISSUE THREAD

**Issue by Valour34** [pipliz/ColonySurvival#59]
Ok so some of my players fields are only growing half of the wheat the NPC's plant. I can confirm this after watching 2 whole in game days and only one side of each field is growing. Im not sure if this is the cause, but i did receive this error on my console.

[2017-08-09_16-57-41][Exception]:Uncaught exception in UnityWrapper.Update:
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

InvalidOperationException: out of sync
  at System.Collections.Generic.Dictionary`2+Enumerator[NetworkID,Colony].VerifyState () [0x00000] in <filename unknown>:0 
  at System.Collections.Generic.Dictionary`2+Enumerator[NetworkID,Colony].MoveNext () [0x00000] in <filename unknown>:0 
  at Colony.CheckBanners () [0x00000] in <filename unknown>:0 
  at UnityWrapper.Update () [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Pipliz.Log:WriteExceptionInternal(String, Exception)
Pipliz.Log:WriteException(String, Exception)
UnityWrapper:Update()
 
(Filename:  Line: -1)

InvalidOperationException: out of sync
  at System.Collections.Generic.Dictionary`2+Enumerator[NetworkID,Colony].VerifyState () [0x00000] in <filename unknown>:0 
  at System.Collections.Generic.Dictionary`2+Enumerator[NetworkID,Colony].MoveNext () [0x00000] in <filename unknown>:0 
  at Colony.CheckBanners () [0x00000] in <filename unknown>:0 
  at UnityWrapper.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

**Comment by pipliz** [comment]
I'll take a better look later, but are you running any mods?

**Comment by Valour34** [comment]
Yes, we're running the mod colony++ but they think this is more base game because they've added their own crop growth stuff because they can't touch the base game stuff.

**Comment by Valour34** [comment]
[Update] Ok so it seems after digging up the crops that seem to be stuck on growing any further and allowing the NPC's to replant them allow them to grow again. I'm not sure however if this fixes it, as some players online seem to say that after a while, they stop growing again.

**Comment by Valour34** [comment]
![image](https://user-images.githubusercontent.com/30879207/29146033-442a5a3a-7d14-11e7-82f7-172636b9db02.png)
 This is a photo of what im watching atm. the far left crops on this plot and the newly planted crops are the only ones that grow. I'll provide another screenshot in a few minutes after growth

**Comment by Valour34** [comment]
![image](https://user-images.githubusercontent.com/30879207/29146390-c41692ee-7d15-11e7-812d-038324c292c9.png)

 Notice how both the left crops and the crops that were just sapplings have grown but not the others "notice the background crops too"

**Comment by tommykent1210** [comment]
Yeah, shouldn't be a colonyplusplus issue, we had to write our own croptracker for our custom crops because the basegame is closed off. We're currently testing our latest build with a game (rare we get to play these days xD) and wheat is growing fine.

**Comment by Valour34** [comment]
would an unexpected shutdown of the console cause this? Just thinking of possibilities.

**Comment by pipliz** [comment]
Possibly, yes. An unexpected shutdown (mostly killing via task manager or power outage, possibly shutting down the computer without stopping the server first) can prevent the game from saving various things. This includes some data attached to wheat to make it grow.

But typical for that would be that all wheat stopped growing. Weirdest would be that they stop growing again after replanting.

Are there any other errors/exceptions in the log? The error you posted is quite weird (not sure how it's caused, the only case would be trying to get a Colony that doesn't exist within the code for checking siege mode - but it only checks that on existing colonies...), but shouldn't be causing any bugs.

**Comment by pipliz** [comment]
P.S; If your world is populated/large enough to stress the server significantly (like 10 fps or lower) I'd appreciate it if you could send a copy to us for checking it out. I haven't checked a populated multiplayer worlds' performance yet. If it fits as an attachment here, that's okay. Otherwise try an email (pipliznl @ gmail.com) or 3rd party hosting. Only the savegame folder is okay.

**Comment by Valour34** [comment]
As far as any other errors/exceptions, i checked the logs and that was the only one present. No errors occurred upon server startup either. As far as any stress on the server, there really hasn't been any. The system i run my server on can pretty much run everyone with a 150 pop cap. The only time NPC rubberbanding occured was when the server hit over 7000 colonists, and normally occured at night when 1 zombie per NPC was spawned. We recently put in a 150 cap mod that limits players to 150 colonists to reduce stress on the server (last time we had 3 people with over 1000 colonists.

**Comment by Valour34** [comment]
would you still like it?

**Comment by pipliz** [comment]
I have since received it I believe :) (Atleast, I think it was yours)

**Comment by pipliz** [comment]
See #61 (likely)
