### ISSUE TITLE
Savegame bugs after power outage / server crash

### ISSUE THREAD

**Issue by TonyW1001** [pipliz/ColonySurvival#61]
I'm running the 0.3.0 version of the game after having a power outage while playing I restarted my saved game to find that all my colonists apart from farmers and miners had gone, all of the positions were still there but don't read has having a free job  
![20170819095504_1](https://user-images.githubusercontent.com/31155437/29485133-a06fad56-84c4-11e7-92f4-f74b77553c4d.jpg)
This includes all my guards!!!!!

**Comment by TonyW1001** [comment]
got it working right now. had to uninstall delete all files ( after copying my savegame) and then reinstall had to then rehire everyone but at least it worked

**Comment by pipliz** [comment]
Thanks for reporting. The game currently autosaves the blocks themselves, but does not autosave the npc / 'job' data or any 'interactive' parts of blocks. So if the game unexpectedly closes (stops working, freezes, power outage) there is some discontinuity between the ingame blocks and the colonists. That causes various bugs to occur.

It's not an easy thing to fix and relatively uncommon, so it is not a very large priority. I will definitely take a look though!

**Comment by Dallarius** [comment]
The prob, I also had, was, that blocks will be saved regular, but player-data not - it will only be saved on player-exiting or server-stop. If the server crashes, only blocks are saved, but no player-data like inventory, jobs and more. 

So it would help to save players-data not only on exiting but in the same cycle like blocks... with prio of players actually playing. What about an totally autosave every few minutes? I think it will be enough and solve these annoying errors.... (other games does it also like this).

**Comment by pipliz** [comment]
Seems to be fixed for about 95%+ by now (autosaves player data, doesn't corrupt files if it crashes while writing one)
