### ISSUE TITLE
Multiplayer bug

### ISSUE THREAD

**Issue by Chairlegmydude** [pipliz/ColonySurvival#71]
Me and my friend were playing fine yesterday but with the new update whoever isn't the host is unable to place blocks, just thought i should inform you, it's not our connection or our PC's because it's been fine for the last 3 days, hope you can patch soonish :) (steam nonpublic)

**Comment by pipliz** [comment]
Can you upload the log files from the server and/or the client? They should be in the game directory (/log/client/ and /log/server/). They're named with the time upon closing the game/server, the most useful one would be where this issue occured.
