### ISSUE TITLE
Stockpile Issues

### ISSUE THREAD

**Issue by Flying8ball** [pipliz/ColonySurvival#72]
Ok I have a colony of 50 and since the update of 3.0 i can not view my stockpile all i see is a white square

**Comment by pipliz** [comment]
Thanks for reporting. Can you upload the log file from /log/client/ (in the game install directory) with the time closest after this issue occured? The logfile from /log/server/ would also be useful if this was on singleplayer (or hosted on your install).

**Comment by Flying8ball** [comment]
I fixed the issue by validating the files in steam will be getting the files to you soon

**Comment by Flying8ball** [comment]
Here are the files
[2017-08-26_08-48-18.txt](https://github.com/pipliz/ColonySurvival/files/1253977/2017-08-26_08-48-18.txt)

**Comment by Flying8ball** [comment]
[2017-08-26_08-46-06.txt](https://github.com/pipliz/ColonySurvival/files/1253978/2017-08-26_08-46-06.txt)

**Comment by pipliz** [comment]
> The file 'C:/Program Files (x86)/Steam/steamapps/common/Colony Survival/colonyclient_Data/level7' is corrupted! Remove it and launch unity again!

Seems like something went wrong in the update process, glad to hear it's fixed
