### ISSUE TITLE
Partial Rollback - Asynchronous saves

### ISSUE THREAD

**Issue by imbleu** [pipliz/ColonySurvival#73]
So I had a sudden loss of power during a storm which forced the computer to shut down without a save on exit. When I logged back in I noticed that my population had decreased to an earlier state (60 colonists, 63 beds, 0 unemployed). However the map and my inventory did not have a rollback so I had about an extra 15 furnaces/mints/ovens etc and an extra 40 beds that were not reading. I found that when I picked up and replaced these objects it did not count them as jobs but if I put them in stockpile and took them out it did so I increased my population back to 75 colonists, 100 beds. My Issue now is that I had moved my job room somewhere between these two saves so I have colonists standing in the middle of the room doing jobs but without the block there. I have tried replacing a new mint in front of the people "minting in thin air" and removing it but it did not work. I tried blocking off the area and I had 10 colonists who were trapped with no path. It seems I am unable to get these colonists fixed and cant refresh their jobs or remove the invisible jobs.

I have also noticed that the farms that were managed by some of the expansion that did not save are still there, however the job doesn't exist and the crops are not growing, despite being half grown.
![screenshot_5](https://user-images.githubusercontent.com/31377816/29746177-be433748-8ac9-11e7-8e24-c6510bc663e8.png)
![screenshot_6](https://user-images.githubusercontent.com/31377816/29746176-be3c1792-8ac9-11e7-8df0-d252319d9f88.png)
![screenshot_8](https://user-images.githubusercontent.com/31377816/29746189-e1f9ad5c-8ac9-11e7-863c-6130f3913d69.png)

Admin User
Windows 10 Pro 64bit
i7-7700k, 32GB DDR4, NVMe SSD, GTX1070.

**Comment by pipliz** [comment]
See issue #61 as well

**Comment by imbleu** [comment]
@pipliz I read through that too and we have very similar issues however I was wondering if there is any form of command (or mod you know of) which refreshes all colonists or any way I can remove these colonists and rehire as I am unsure what they are actually doing.

**Comment by pipliz** [comment]
There isn't, sorry :(

There are ideas to fix it in the future, but it's a quite complex issue to fix without ruining performance.

**Comment by pipliz** [comment]
Again, #61
